spring.application.name=user
spring.config.import=optional:application-secret.properties

spring.datasource.url=jdbc:postgresql://localhost:5436/user_db
spring.datasource.username=postgres
spring.datasource.password=BYC-eM5-Mzw-Mp8

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.profiles.active=dev